name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 1.0.0-rc.2
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  coverage: ^1.0.3
  quill_delta: ^3.0.0-nullsafety.1
  quiver: ^3.0.1

dev_dependencies:
  test: ^1.10.0
  lints: ^1.0.1
