name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0-dev.2.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^6.0.0
  quill_delta: ^2.0.0
  notus:
    git:
      url: https://github.com/hokutoresident/zefyr
      ref: hokuto
      path: packages/notus
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0
  characters: ^1.0.0
  google_fonts: ^2.1.0
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
