name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0-rc.5
homepage: https://github.com/memspace/zefyr
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
 collection: 1.17.1
 url_launcher: ^6.1.6
 quill_delta: ^3.0.0-nullsafety.2

 notus:
   git:
     url: https://github.com/memspace/zefyr
     path: packages/notus
     ref: 6f9281913c8f8699444a745cf8ada92a87c6a908

 characters: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
