name: test_notus

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - 1.0-dev
      - hokuto
      - feature/run-test-on-ci

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.0"

      - name: Test notus
        run: |
          cd packages/notus/
          flutter pub get
          flutter test

      - name: Send Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
          SLACK_TITLE: Test Success
          SLACK_MESSAGE: ":white_check_mark:[notus]全てのテストが成功しました:white_check_mark:"
          SLACK_COLOR: good

      - name: Send Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
          SLACK_TITLE: Test Failure
          SLACK_MESSAGE: |
            :x:[notus]テスト失敗:x:
            どのテストが落ちているか確認し、修正してください。
          SLACK_COLOR: danger
